### ISSUE TITLE
Something looks off with a few colors

### ISSUE THREAD

**Issue by maxcountryman** [brattonross/windy-radix-palette#15]
I think there's a typo in regarding the blues and so I've opened #14 to address.

However I also noticing that the sky through amber colors on [the site](https://windy-radix-palette.vercel.app) don't seem to be in order of saturation and lightness. (See the right-hand side in the screenshot.) I don't see a typo here, so I want to check this is expected and not a bug.

<img width="1296" alt="Screenshot 2023-02-16 at 10 05 26 AM" src="https://user-images.githubusercontent.com/74351/219450499-d6e4cd4d-3648-4016-9829-e8cb3c343b57.png">

**Comment by italodeandra** [comment]
Hey @maxcountryman,

The `windy-radix-palette` is just a plugin made for TailwindCSS where you can use Radix Colors.

You can check the "real" ones here: https://www.radix-ui.com/colors

And the colors you mentioned seems to be the exact one - see the a screenshot from Radix Colors:

![image](https://user-images.githubusercontent.com/19225266/222777610-d422da58-0ee6-4560-b010-05230ce2fdf7.png)

But nice catch on #14.

**Comment by brattonross** [comment]
As @italodeandra pointed out, this is just how Radix colors are :D You have a keen eye though, thanks for opening the issue!
