### ISSUE TITLE
Dark blue color not working

### ISSUE THREAD

**Issue by frencojobs** [brattonross/windy-radix-palette#2]
In generated `base.css` file, `blue` is imported after `blueDark` unlike other colors.

<img width="365" alt="Screen Shot 2022-08-06 at 11 54 25 PM" src="https://user-images.githubusercontent.com/17830687/183259497-6541e715-9915-48ed-8f52-1b8b73b27d1a.png">

Therefore `:root` blue taking over `.dark` blue. You can reproduce the behavior in firefox and safari. Not sure about chrome though.

**Comment by brattonross** [comment]
Thanks for reporting this. I've been meaning to create a little demo app that shows all of the colors, a bit like the Radix Colors landing page. I think this could also act as a living example of the colors being generated correctly. I'll try to get to this soon.

**Comment by brattonross** [comment]
This should be fixed in v0.1.2!
