### ISSUE TITLE
Jade seems to be missing?

### ISSUE THREAD

**Issue by maxcountryman** [brattonross/windy-radix-palette#20]
I can't see any reason why, but the jade color seems to be missing. Other similar colors, like grass, are present.

**Comment by brattonross** [comment]
Do you have version 2.1.0 of `@radix-ui/colors` installed in your app? The colors Ruby, Jade, and Iris were added in that version

**Comment by maxcountryman** [comment]
I believe so, this is what I've got in my `package.json`: `"@radix-ui/colors": "^2.1.0"` along with `"windy-radix-palette": "^0.6.1"`.

**Comment by brattonross** [comment]
Hey, does this problem still exist for you in the latest 2.0.0 beta release (with Radix Colors v3.0.0)?
Also, do you mind checking that you can see all possible colors at https://windy-radix-palette.vercel.app ?

**Comment by brattonross** [comment]
Closing this for now
