### ISSUE TITLE
When using tailwind config dark mode "class", color palette still decided by device preference

### ISSUE THREAD

**Issue by jsutherland1** [brattonross/windy-radix-palette#24]
Hey! First of all thanks for writing this package, we've been exploring using it for monarchmoney.com.

I was testing the v2.0.0 beta because I was having issues with P3 colors, and noticed that when using `darkMode: ['class']` in the tailwind config, I was always seeing dark mode colors. When I switched my device to light mode, it switched the palette. This shouldn't happen when using 'class' for this setting, only 'media'.

**Comment by brattonross** [comment]
Hey, glad you've found the package useful, personally I can't start a project without it nowadays. The credit should go to the authors of Radix and Tailwind though, this package is really just a little bit of glue between them :smile:

I'll release a new beta version shortly that hopefully addresses your issue
