### ISSUE TITLE
Mutable alias on an entire color scale doesn't work

### ISSUE THREAD

**Issue by cdebotton** [brattonross/windy-radix-palette#27]
Hello! First of all, fantastic plugin! I've noticed that the example for a mutable alias on a scale doesn't work:

```js
const { createPlugin } = require("windy-radix-palette");

const colors = createPlugin();

module.exports = {
	theme: {
		extend: {
			colors: {
				overlay: colors.alias({
					light: "blackA",
					dark: "whiteA",
				}),
			},
		},
	},
};
```

It seems as though the css variables aren't properly generated:

<img width="332" alt="Screenshot 2023-10-26 at 7 15 42 PM" src="https://github.com/brattonross/windy-radix-palette/assets/416880/89266c80-a130-4e55-99f1-6050b008f345">

The generated variable name doesn't exist in the scope of the CSS file. All other forms of aliasing seem to work properly.

I'm using version `2.0.0-beta.5` of the plugin.

UPDATE: Instead of adding `colors.plugin` to the plugins array, everything seems to work as expected when I added `colors.plugin.handler`.

eg)

```diff
const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // Theme config...
-  plugins: [colors.plugin],
+  plugins: [colors.plugin.handler],
};
```

**Comment by brattonross** [comment]
Thanks for spotting this! Looks like it was a copy-paste error on my part. Should be fixed in beta.6 :)
