### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by Jun-Xiang** [brattonross/windy-radix-palette#6]
I tried following the readme in this repo but couldn't get the colors to change when i add `dark` class to either html or body. (I am using it on a react project)
Below is my tailwind config (not all i just put the ones that are important)
`tailwind.config.js`
```module.exports = {
	darkMode: "class",
	content: ["./src/**/*.{js,jsx,ts,tsx}"],
	plugins: [
		require("windy-radix-palette"),
		require("tailwindcss-radix"),
	],
};
```
I tried to compile the css using `npx tailwindcss -i ./src/index.css -o ./dist/output.css --watch` and find `.dark` class but in the compiled css, there's no such class called `dark`. I am not sure what went wrong. It would be helpful if I can get some help. Thanks.

**Comment by brattonross** [comment]
Thank you for opening this issue!

Are you adding the `dark` class to a file that matches the pattern in your `content` option?
If not, it seems that the plugin won't know to use dark colors.

**Comment by Jun-Xiang** [comment]
~Hmm the `docs` example in this repo doesn't have `dark` class in `BaseLayout.astro` (I assume is the layout used in every page) so I thought it will work. 
I want it to be light mode at first tho. Any idea on how should I do it? Thanks.~

Edit: I didn't know tailwind also looks at JS stuff (the code below) to determine classes hmm.
```
const theme = (() => {
	if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
		return "dark";
	}
	return "light";
})();
if (theme === "light") {
	document.documentElement.classList.remove("dark");
	document.documentElement.style.colorScheme = "light";
} else {
	document.documentElement.classList.add("dark");
	document.documentElement.style.colorScheme = "dark";
}
```

~How about If i am using it in storybook how should I set it up?~

Edit 2: I found a way to force tailwind to generate it. (https://tailwindcss.com/docs/content-configuration#safelisting-classes). Thanks for your time.
